"""add travel preferences

Revision ID: 71a9848d9274
Revises: edc4bf60edb8
Create Date: 2026-05-03 12:20:16.859135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71a9848d9274'
down_revision: Union[str, Sequence[str], None] = 'edc4bf60edb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel_preferences',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('home_city', sa.String(length=255), nullable=True),
    sa.Column('home_airport', sa.String(length=16), nullable=True),
    sa.Column('budget_style', sa.String(length=64), nullable=True),
    sa.Column('pace', sa.String(length=32), nullable=True),
    sa.Column('dietary_needs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('travel_preferences')
    # ### end Alembic commands ###
